# Generated by Django 5.0 on 2023-12-28 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование товара')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='описание товара')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(999999999)], verbose_name='цена товара')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', verbose_name='валюта оплаты')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
