# Generated by Django 5.0 on 2023-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_discount_alter_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='налог'),
        ),
    ]
